---
name: Automated Build
run-name: ${{ github.actor }} is building the translation patch... Let's see what happens...
on:
  - push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }}."
       - name: grab tdmextractor
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: envyniv/tdmextractor
      - name: grab tdmfscripteditor
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: denpaintern/tdmfscripteditor
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: do the magic
        run: cd ${{ github.workspace }}
        run: chmod +x ./build.sh; ./build.sh
